### PR TITLE
setup for a maven build #2

### PR DESCRIPTION
**Pull request by ruckc**
This is a mavenized build process for #2

### CODE REVIEW

**Comment by eugener** [comment]
"resources/resources" looks pretty strange. Should be just "resources" with all the resources in the root as in original IMO

**Comment by ruckc** [comment]
I agree, but he was accessing the resources from the classpath, under a resources directory inside the jar, so I left it as is to not require any actual source code changes.

**Comment by eugener** [comment]
I would suggest making a code change as the project structure is changing drastically anyway

**Comment by alexbodogit** [comment]
I am not very expert maven or Gradle. so I would be honored to let you choose, also to change the structure of the project

**Comment by eugener** [comment]
Either one is OK.. It usually depends on personal preferences. Related pull request looks good IMO and will convert your project to a maven project as soon as you merge it. 

Also you have to choose an appropriate license for your project. I would suggest [BSD 3-Clause License](https://opensource.org/licenses/BSD-3-Clause)

**Pull request merged**
